Repository Materka11/jadoo_landing_page, pull requests merged in 2025-02, with the labels that each got.

#28 Fix: Translations
  src/config/i18n.ts
Labels: bug

#29 Docs: Add live demo section to README
  README.md
Labels: documentation

#30 Feature: Category headers
  eslint.config.js
  src/components/organisms/Category.tsx
  src/components/templates/HomeTemplate.tsx
  src/index.css
  src/stories/organisms/Category.stories.tsx
Labels: enhancement

#31 Feature: Category Card
  src/components/atoms/CategoryCard.tsx
  src/components/atoms/PlaneWithRectangleIcon.tsx
  src/components/organisms/Category.tsx
  src/index.css
  src/stories/atoms/CategoryCard.stories.tsx
  src/stories/atoms/PlaneWithRectangleIcon.stories.tsx
Labels: enhancement

#32 Feature/main content
  src/assets/image/traveller.webp
  src/components/atoms/BackgroundImage.tsx
  src/components/atoms/Button.tsx
  src/components/atoms/ContentText.tsx
  src/components/atoms/MainContentImage.tsx
  src/components/atoms/PlaneImage.tsx
  src/components/atoms/PlayDemo.tsx
  src/components/atoms/RectangleButton.tsx
  src/components/atoms/TextRectangle.tsx
  src/components/atoms/Triangle.tsx
  src/components/molecules/Card.tsx
  src/components/organisms/CardList.tsx
  src/components/organisms/Header.tsx
  src/components/organisms/MainContent.tsx
  src/components/templates/HomeTemplate.tsx
  src/index.css
  src/molecules/TextAndButtons.tsx
  src/stories/atoms/BackgroundImage.stories.tsx
  src/stories/atoms/Button.stories.tsx
  src/stories/atoms/ContentText.stories.tsx
  src/stories/atoms/MainContent.stories.tsx
  src/stories/atoms/PlaneImage.stories.tsx
  src/stories/atoms/PlayDemo.stories.tsx
  src/stories/atoms/RecatngleButton.stories.tsx
  src/stories/atoms/TextRectangle.stores.tsx
  src/stories/atoms/Triangle.storeis.tsx
  src/stories/molecules/Card.stories.tsx
  src/stories/organisms/CardList.stories.tsx
  src/stories/organisms/MainContent.stories.tsx
  src/stories/organisms/TextAndButton.stories.tsx
Labels: enhancement

#33 Feature: Category Card List
  .gitignore
  README.md
  src/components/atoms/AppStore.tsx
  src/components/atoms/CategoryCard.tsx
  src/components/atoms/FacebookIcon.tsx
  src/components/atoms/GooglePlayIcon.tsx
  src/components/atoms/InstagramIcon.tsx
  src/components/atoms/MicWithRectangleIcon.tsx
  src/components/atoms/PlaneWithRectangleIcon.tsx
  src/components/atoms/SatelliteWithRectangleIcon.tsx
  src/components/atoms/SprocketWithRectangleIcon.tsx
  src/components/molecules/CategoryListCard.tsx
  src/components/organisms/Category.tsx
  src/stories/atoms/CategoryCard.stories.tsx
  src/stories/atoms/MicWithRectangleIcon.stories.tsx
  src/stories/atoms/SatelliteWithRectangleIcon.stories.tsx
  src/stories/atoms/SprocketWithRectangleIcon.stories.tsx
  src/stories/molecules/CategoryListCard.stories.tsx
  tsconfig.tsbuildinfo
Labels: enhancement

#34 Feature: Category bg image
  src/assets/image/Bg1.webp
  src/components/atoms/Headers.tsx
  src/components/organisms/Category.tsx
  src/components/templates/HomeTemplate.tsx
Labels: enhancement

#40 Feature: Category
  eslint.config.js
  src/assets/image/Bg1.webp
  src/components/atoms/AppStore.tsx
  src/components/atoms/CategoryCard.tsx
  src/components/atoms/FacebookIcon.tsx
  src/components/atoms/GooglePlayIcon.tsx
  src/components/atoms/Headers.tsx
  src/components/atoms/InstagramIcon.tsx
  src/components/atoms/MicWithRectangleIcon.tsx
  src/components/atoms/PlaneWithRectangleIcon.tsx
  src/components/atoms/SatelliteWithRectangleIcon.tsx
  src/components/atoms/SprocketWithRectangleIcon.tsx
  src/components/molecules/CategoryListCard.tsx
  src/components/organisms/Category.tsx
  src/components/templates/HomeTemplate.tsx
  src/index.css
  src/stories/atoms/CategoryCard.stories.tsx
  src/stories/atoms/MicWithRectangleIcon.stories.tsx
  src/stories/atoms/PlaneWithRectangleIcon.stories.tsx
  src/stories/atoms/SatelliteWithRectangleIcon.stories.tsx
  src/stories/atoms/SprocketWithRectangleIcon.stories.tsx
  src/stories/molecules/CategoryListCard.stories.tsx
  src/stories/organisms/Category.stories.tsx
Labels: enhancement

#41 Feature: Easy and fast headers
  src/components/organisms/EasyAndFast.tsx
  src/components/organisms/MainContent.tsx
  src/components/templates/HomeTemplate.tsx
  src/index.css
Labels: enhancement

#42 Feature/top selling card
  package-lock.json
  package.json
  src/assets/image/cursorVector.webp
  src/assets/image/fullEurope.webp
  src/assets/image/london.webp
  src/assets/image/rome.webp
  src/components/atoms/ContentText.tsx
  src/components/atoms/TopDestinationsCard.tsx
  src/helpers/ConvertDaysToDay.ts
  src/index.css
  src/stories/atoms/TopDestinationsCard.stories.tsx
Labels: enhancement

#43 Feature: List Element
  src/components/atoms/ChooseDestinationIcon.tsx
  src/components/atoms/ListElement.tsx
  src/components/organisms/EasyAndFast.tsx
  src/stories/atoms/ChooseDestinationIcon.stories.tsx
  src/stories/atoms/ListElement.stories.tsx
Labels: enhancement

#44 Feature: Post
  package-lock.json
  package.json
  src/assets/image/PostImage.webp
  src/assets/image/ProfileProgress.webp
  src/components/atoms/BuildingIcon.tsx
  src/components/atoms/HeartIcon.tsx
  src/components/atoms/LeafIcon.tsx
  src/components/atoms/MapIcon.tsx
  src/components/atoms/SendIcon.tsx
  src/components/atoms/TripPost.tsx
  src/components/atoms/TripProgress.tsx
  src/components/molecules/ExampleTrip.tsx
  src/components/organisms/EasyAndFast.tsx
  src/components/templates/HomeTemplate.tsx
  src/index.css
  src/stories/atoms/BuildingIcon.stories.tsx
  src/stories/atoms/HeartIcon.stories.tsx
  src/stories/atoms/LeafIcon.stories.tsx
  src/stories/atoms/MapIcon.stories.tsx
  src/stories/atoms/SendIcon.stories.tsx
  src/stories/atoms/TripPost.stories.tsx
  src/stories/atoms/TripProgress.stories.tsx
  src/stories/molecules/ExampleTrip.stories.tsx
Labels: enhancement

#49 Feature: List
  src/components/atoms/ListElement.tsx
  src/components/atoms/MainContentImage.tsx
  src/components/atoms/PaymentIcon.tsx
  src/components/atoms/ReachAirportIcon.tsx
  src/components/molecules/List.tsx
  src/components/organisms/EasyAndFast.tsx
  src/stories/atoms/ListElement.stories.tsx
  src/stories/atoms/PaymentIcon.stories.tsx
  src/stories/atoms/ReachAirportIcon.stories.tsx
  src/stories/molecules/List.stories.tsx
Labels: enhancement

#50 Feature: Left Side
  src/components/molecules/List.tsx
  src/components/organisms/EasyAndFast.tsx
  src/components/templates/HomeTemplate.tsx
Labels: enhancement

#52 Feature: easy and fast
  package-lock.json
  package.json
  src/assets/image/PostImage.webp
  src/assets/image/ProfileProgress.webp
  src/components/atoms/BuildingIcon.tsx
  src/components/atoms/ChooseDestinationIcon.tsx
  src/components/atoms/HeartIcon.tsx
  src/components/atoms/LeafIcon.tsx
  src/components/atoms/ListElement.tsx
  src/components/atoms/MapIcon.tsx
  src/components/atoms/PaymentIcon.tsx
  src/components/atoms/ReachAirportIcon.tsx
  src/components/atoms/SendIcon.tsx
  src/components/atoms/TripPost.tsx
  src/components/atoms/TripProgress.tsx
  src/components/molecules/ExampleTrip.tsx
  src/components/molecules/List.tsx
  src/components/organisms/EasyAndFast.tsx
  src/components/organisms/MainContent.tsx
  src/components/templates/HomeTemplate.tsx
  src/index.css
  src/stories/atoms/BuildingIcon.stories.tsx
  src/stories/atoms/ChooseDestinationIcon.stories.tsx
  src/stories/atoms/HeartIcon.stories.tsx
  src/stories/atoms/LeafIcon.stories.tsx
  src/stories/atoms/ListElement.stories.tsx
  src/stories/atoms/MapIcon.stories.tsx
  src/stories/atoms/PaymentIcon.stories.tsx
  src/stories/atoms/ReachAirportIcon.stories.tsx
  src/stories/atoms/SendIcon.stories.tsx
  src/stories/atoms/TripPost.stories.tsx
  src/stories/atoms/TripProgress.stories.tsx
  src/stories/molecules/ExampleTrip.stories.tsx
  src/stories/molecules/List.stories.tsx
  src/stories/organisms/EasyAndFast.stories.tsx
Labels: enhancement

#53 Feature: Headers
  src/components/organisms/Testimonials.tsx
Labels: enhancement

#55 Feature: vertical slider
  package-lock.json
  package.json
  src/assets/image/Avatar.webp
  src/components/atoms/ChevronTop.tsx
  src/components/atoms/Testimonial.tsx
  src/components/molecules/VerticalSlider.tsx
  src/components/organisms/Testimonials.tsx
  src/stories/atoms/Testimonial.stories.tsx
  src/stories/molecules/VerticalSlider.stories.tsx
Labels: enhancement

#56 Feature: Form
  src/assets/image/Arrow.webp
  src/assets/image/BgForm.webp
  src/components/atoms/EmailIcon.tsx
  src/components/atoms/FormInput.tsx
  src/components/atoms/RectangleButton.tsx
  src/components/molecules/Form.tsx
  src/components/templates/HomeTemplate.tsx
  src/stories/atoms/EmailIcon.stories.tsx
  src/stories/atoms/FormInput.stories.tsx
  src/stories/atoms/RecatngleButton.stories.tsx
  src/stories/molecules/Form.stories.tsx
Labels: enhancement

#58 Feature: testimonials
  src/assets/image/Avatar.webp
  src/components/atoms/ChevronTop.tsx
  src/components/atoms/Testimonial.tsx
  src/components/molecules/VerticalSlider.tsx
  src/components/organisms/Testimonials.tsx
  src/components/organisms/TopSelling.tsx
  src/components/templates/HomeTemplate.tsx
  src/stories/atoms/MainContent.stories.tsx
  src/stories/atoms/PlaneImage.stories.tsx
  src/stories/atoms/Testimonial.stories.tsx
  src/stories/molecules/VerticalSlider.stories.tsx
  src/stories/organisms/Testimonials.stories.tsx
  src/stories/organisms/TopSelling.stories.tsx
Labels: enhancement

#59 Feature: form
  src/assets/image/Arrow.webp
  src/assets/image/BgForm.webp
  src/components/atoms/EmailIcon.tsx
  src/components/atoms/FormInput.tsx
  src/components/atoms/PlayDemo.tsx
  src/components/atoms/RectangleButton.tsx
  src/components/organisms/Category.tsx
  src/components/organisms/Form.tsx
  src/components/templates/HomeTemplate.tsx
  src/stories/atoms/EmailIcon.stories.tsx
  src/stories/atoms/FormInput.stories.tsx
  src/stories/atoms/RecatngleButton.stories.tsx
  src/stories/organisms/Form.stories.tsx
Labels: enhancement

#61 Fix: Left Align
  src/components/atoms/ContentText.tsx
  src/components/atoms/TextRectangle.tsx
  src/components/molecules/TextAndButtons.tsx
  src/stories/atoms/TextRectangle.stores.tsx
  src/stories/atoms/TextRectangle.stories.tsx
Labels: bug

#63 Fix: Login animation
  src/components/atoms/BackgroundImage.tsx
  src/components/organisms/Header.tsx
Labels: bug

#64 Feature: SocialLinks animation
  src/components/atoms/AppStore.tsx
  src/components/atoms/SocialIcon.tsx
Labels: enhancement

#67 Feature: Enhance SEO and Performance
  index.html
  package.json
  public/android-chrome-192x192.webp
  public/android-chrome-512x512.webp
  public/apple-touch-icon.webp
  public/favicon-16x16.webp
  public/favicon-32x32.webp
  public/favicon.ico
  public/site.webmanifest
  robots.txt
  sitemap.xml
  src/components/atoms/ChevronTop.tsx
  src/components/atoms/EmailIcon.tsx
  src/components/atoms/HamburgerIcon.tsx
  src/components/atoms/LeafIcon.tsx
  src/components/atoms/Logo.tsx
  src/components/atoms/MainContentImage.tsx
  src/components/atoms/MapIcon.tsx
  src/components/atoms/PlayDemo.tsx
  src/components/atoms/Testimonial.tsx
  src/components/atoms/TopDestinationsCard.tsx
  src/components/atoms/TripPost.tsx
  src/components/atoms/TripProgress.tsx
  src/components/molecules/List.tsx
  src/components/molecules/TopDestinationListCard.tsx
  src/components/molecules/VerticalSlider.tsx
  src/components/organisms/Category.tsx
  src/components/organisms/Footer.tsx
  src/components/organisms/Form.tsx
  src/components/organisms/LogosSection.tsx
  src/index.css
  vite.config.ts
Labels: enhancement

#69 Fixed: Updated autoplay delay and speed in LogosSection component
  src/components/organisms/LogosSection.tsx
Labels: bug

#68 Fix/add additional translations
  public/locales/en/translation.json
  public/locales/pl/translation.json
  src/components/atoms/ContentText.tsx
  src/components/atoms/Navlinks.tsx
  src/components/atoms/PlayDemo.tsx
  src/components/atoms/TopDestinationsCard.tsx
  src/components/atoms/TopSellingText.tsx
  src/components/atoms/TripPost.tsx
  src/components/atoms/TripProgress.tsx
  src/components/molecules/ExampleTrip.tsx
  src/components/molecules/Socials.tsx
  src/components/molecules/TextAndButtons.tsx
  src/components/molecules/VerticalSlider.tsx
  src/components/organisms/Category.tsx
  src/components/organisms/EasyAndFast.tsx
  src/components/organisms/Footer.tsx
  src/components/organisms/Testimonials.tsx
  src/components/templates/HomeTemplate.tsx
  src/data/destinations.ts
  src/helpers/convertDaysToDay.ts
Labels: bug

#71 Fix: Updated HomeTemplate component to increase maximum width and adj…
  src/components/templates/HomeTemplate.tsx
Labels: bug
